name: n8n
services:
  postgresql:
    container_name: n8n-postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    networks:
      - n8n-network
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U n8n -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    container_name: n8n-server
    image: docker.n8n.io/n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
    networks:
      - n8n-network
    ports:
      - 5678:5678
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      postgresql:
        condition: service_healthy

networks:
  n8n-network:
    driver: bridge
    name: n8n-network